### ISSUE TITLE
Install CFSSL fail

### ISSUE THREAD

**Issue by essie-chiang** [JackyZhangFuDan/K8sSourceCodeDeepDive#1]
Hi Jacky,

I am following your instruction to setup kube dev env, could not success install CFSSL, with proxy set as 
```
go env -w GO111MODULE="on"  
go env -w GOPROXY="https://goproxy.cn,direct"  
```
The error output is:
```shell
go install github.com/cloudflare/cfssl/cmd/...@latest  
go: github.com/cloudflare/cfssl/cmd/...@latest: module github.com/cloudflare/cfssl/cmd: Get "https://goproxy.cn/github.com/cloudflare/cfssl/cmd/@v/list": dial tcp 146.112.61.106:443: connect: connection refused
```

Any suggestion for this issue?

**Comment by essie-chiang** [comment]
Change to other proxy and success... 
export GOPROXY=https://proxy.golang.com.cn,direct

**Comment by JackyZhangFuDan** [comment]
:-), happy to know that. 
yes I had similar experience with golang proxy, sometimes we just need to change from one to another.

BTW, I just tried with https://goproxy.cn,direct, the install cmd works fine.... I use 中国电信.
